name: CI/CD to GKE (Python)

on:
  push:
    branches: ["week07_7.2H"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r book_catalog/requirements.txt
          pip install parsimonious --upgrade

      - name: Run tests
        run: |
          PYTHONPATH=. pytest

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REGISTRY }}/book-catalog:1 .

      - name: Push Docker image to Artifact Registry
        run: docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REGISTRY }}/book-catalog:1

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GCP_REGION }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f scripts/deployment.yaml

      - name: Verify Kubernetes resources
        run: |
          kubectl get pods
          kubectl get services
          kubectl get deployment
